apiVersion: v1
kind: Service
metadata:
  name: frontend-react-app-service
spec:
  type: LoadBalancer
  selector:
    app: frontend-react-app
  ports:
    - protocol: TCP
      port: 50001
      targetPort: 80